### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by bovine3dom** [philoez98/Turf.jl#15]
Hey @philoez98, I finally got round to maintaining this repo a little bit.

It looks like the way we make releases has changed a bit since you last did it - could you install the Registrator action on this repo - https://github.com/JuliaRegistries/Registrator.jl/#registrator ?

Thanks!

**Comment by philoez98** [comment]
Hi, the registrator should be up and running. Let me know if something else is needed.

**Comment by bovine3dom** [comment]
Looks like it worked, 0.2.1 has been released. Thanks!

https://github.com/JuliaRegistries/General/pull/38278
