### ISSUE TITLE
Calling masscenter with a LineString calculates the mean center, not the center of mass

### ISSUE THREAD

**Issue by samuelkim314** [philoez98/Turf.jl#18]
**Describe the bug**
The `masscenter` function on a `LineString` object actually calculates the mean center (called the centroid in this code), not the center of mass. The latter is the expected behavior based on the documentation.

**To Reproduce**
```julia
using Turf
line = LineString([[1, 2], [4, 6], [8, 9.5], [12, 13.4]])
println(Turf.masscenter(line))
```

**Expected behavior**
I expect the output
```
Point([5.211 , 6.646])
```
However, it returns
```
Point([6.25, 7.725])
```
which is the *mean center*, not the center of mass.

I suspect that it has to do with the unfinished `else` statement in the code, which just reverts to calculating the mean center. https://github.com/philoez98/Turf.jl/blob/2dc2c385f860204552b9a2bcba7edeb9f723b710/src/lib/Centering.jl#L176-L181

**Desktop (please complete the following information):**
 - OS: Windows 10 with WSL: Ubuntu
 - Julia version 1.6.1
 - Turf.jl version 0.2.1

**Comment by samuelkim314** [comment]
I made a pull request fixing this. https://github.com/philoez98/Turf.jl/pull/19

**Comment by philoez98** [comment]
Merged your PR. Thanks!
