### ISSUE TITLE
GeoJSON will switch from JSON to JSON3

### ISSUE THREAD

**Issue by yeesian** [philoez98/Turf.jl#6]
Just wanted to give you a heads-up on https://github.com/JuliaGeo/GeoJSON.jl/pull/22.

**Comment by philoez98** [comment]
@yeesian thanks. There will be api changes other than reading/writing json with JSON3?

**Comment by yeesian** [comment]
To my understanding, the api changes are to change `GeoJSON.parse` to `GeoJSON.read`, and `GeoJSON.geojson` to `GeoJSON.write`. The structures that are returned might be slightly different in their types too.

(The PR has not been merged, and it has not made it into a release . I just opened this issue to let you know the discussion is being had.)

**Comment by philoez98** [comment]
I'll be keeping an eye on that! Thanks :+1:

**Comment by visr** [comment]
> There will be api changes other than reading/writing json with JSON3?

I think if we are going to do a breaking release, it might make more sense to include https://github.com/JuliaGeo/GeoJSON.jl/issues/21 as well.

Feel free to weight in on any of the discussions, your feedback is very much appreciated!
